export const ACHIEVEMENTS = [
  {
    id: 'first-blood',
    name: 'First Blood',
    description: 'Complete your very first workout',
    icon: 'Swords',
    rarity: 'common',
    conditionLabel: 'Complete 1 workout',
  },
  {
    id: 'double-digits',
    name: 'Double Digits',
    description: 'Complete 10 workouts total',
    icon: 'Hash',
    rarity: 'common',
    conditionLabel: 'Complete 10 workouts',
  },
  {
    id: 'century',
    name: 'Centurion',
    description: 'Complete 100 workouts — a true warrior',
    icon: 'Shield',
    rarity: 'epic',
    conditionLabel: 'Complete 100 workouts',
  },
  {
    id: 'week-warrior',
    name: 'Week Warrior',
    description: 'Maintain a 7-day workout streak',
    icon: 'Flame',
    rarity: 'rare',
    conditionLabel: '7-day streak',
  },
  {
    id: 'month-grind',
    name: 'Month of Pain',
    description: 'Maintain a 30-day workout streak',
    icon: 'Calendar',
    rarity: 'epic',
    conditionLabel: '30-day streak',
  },
  {
    id: 'iron-will',
    name: 'Iron Will',
    description: 'Maintain a 100-day workout streak — legendary dedication',
    icon: 'Zap',
    rarity: 'legendary',
    conditionLabel: '100-day streak',
  },
  {
    id: 'rep-machine',
    name: 'Rep Machine',
    description: 'Accumulate 1000 total reps across all workouts',
    icon: 'Repeat',
    rarity: 'rare',
    conditionLabel: '1000 total reps',
  },
  {
    id: 'heavy-lifter',
    name: 'Heavy Lifter',
    description: 'Complete a single set with 100kg or more',
    icon: 'Dumbbell',
    rarity: 'rare',
    conditionLabel: 'Lift 100kg in one set',
  },
  {
    id: 'cardio-bunny',
    name: 'Cardio Bunny',
    description: 'Log 60 minutes of cardio in a single session',
    icon: 'Heart',
    rarity: 'rare',
    conditionLabel: '60 min cardio in one session',
  },
  {
    id: 'marathon-mind',
    name: 'Marathon Mind',
    description: 'Run a total of 42km across all sessions',
    icon: 'MapPin',
    rarity: 'epic',
    conditionLabel: '42km total running distance',
  },
  {
    id: 'level-5',
    name: 'Power Awakening',
    description: 'Reach Level 5 — your journey truly begins',
    icon: 'Star',
    rarity: 'common',
    conditionLabel: 'Reach Level 5',
  },
  {
    id: 'level-10',
    name: 'Legendary Status',
    description: 'Reach Level 10 — join the elite',
    icon: 'Crown',
    rarity: 'epic',
    conditionLabel: 'Reach Level 10',
  },
  {
    id: 'xp-hoarder',
    name: 'XP Hoarder',
    description: 'Accumulate 10,000 total XP',
    icon: 'Sparkles',
    rarity: 'rare',
    conditionLabel: '10,000 total XP',
  },
  {
    id: 'quest-starter',
    name: 'Quest Starter',
    description: 'Complete your first daily quest',
    icon: 'Scroll',
    rarity: 'common',
    conditionLabel: 'Complete 1 daily quest',
  },
  {
    id: 'quest-machine',
    name: 'Quest Machine',
    description: 'Complete 50 daily quests total',
    icon: 'CheckSquare',
    rarity: 'rare',
    conditionLabel: 'Complete 50 daily quests',
  },
  {
    id: 'variety-pack',
    name: 'Jack of All Trades',
    description: 'Train 5 different muscle groups in a single workout',
    icon: 'Layers',
    rarity: 'rare',
    conditionLabel: '5 muscle groups in one workout',
  },
  {
    id: 'early-bird',
    name: 'Early Bird',
    description: 'Start a workout before 7:00 AM',
    icon: 'Sunrise',
    rarity: 'common',
    conditionLabel: 'Workout before 7 AM',
  },
  {
    id: 'night-owl',
    name: 'Night Owl',
    description: 'Start a workout after 10:00 PM',
    icon: 'Moon',
    rarity: 'common',
    conditionLabel: 'Workout after 10 PM',
  },
  {
    id: 'class-chosen',
    name: 'Chosen One',
    description: 'Select your character class and forge your destiny',
    icon: 'UserCheck',
    rarity: 'common',
    conditionLabel: 'Select a character class',
  },
  {
    id: 'weekly-sweep',
    name: 'Weekly Sweep',
    description: 'Complete all weekly quests in a single week',
    icon: 'Trophy',
    rarity: 'legendary',
    conditionLabel: 'Complete all weekly quests in one week',
  },
];

export const RARITY_COLORS = {
  common: '#9ca3af',
  rare: '#2563eb',
  epic: '#7c3aed',
  legendary: '#f59e0b',
};

export const RARITY_GLOW = {
  common: 'rgba(156, 163, 175, 0.4)',
  rare: 'rgba(37, 99, 235, 0.5)',
  epic: 'rgba(124, 58, 237, 0.5)',
  legendary: 'rgba(245, 158, 11, 0.6)',
};
