export const EXERCISES = [
  {
    id: 'barbell-squat',
    name: 'Barbell Squat',
    category: 'strength',
    muscleGroups: ['quads', 'glutes', 'hamstrings', 'core'],
    isBodyweight: false,
  },
  {
    id: 'deadlift',
    name: 'Deadlift',
    category: 'strength',
    muscleGroups: ['hamstrings', 'glutes', 'back', 'core'],
    isBodyweight: false,
  },
  {
    id: 'bench-press',
    name: 'Bench Press',
    category: 'strength',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    isBodyweight: false,
  },
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    category: 'strength',
    muscleGroups: ['shoulders', 'triceps', 'core'],
    isBodyweight: false,
  },
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    category: 'strength',
    muscleGroups: ['back', 'biceps', 'core'],
    isBodyweight: false,
  },
  {
    id: 'pull-up',
    name: 'Pull-up',
    category: 'strength',
    muscleGroups: ['back', 'biceps', 'core'],
    isBodyweight: true,
  },
  {
    id: 'push-up',
    name: 'Push-up',
    category: 'strength',
    muscleGroups: ['chest', 'shoulders', 'triceps', 'core'],
    isBodyweight: true,
  },
  {
    id: 'dips',
    name: 'Dips',
    category: 'strength',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    isBodyweight: true,
  },
  {
    id: 'lunges',
    name: 'Lunges',
    category: 'strength',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    isBodyweight: true,
  },
  {
    id: 'plank',
    name: 'Plank',
    category: 'strength',
    muscleGroups: ['core', 'shoulders'],
    isBodyweight: true,
  },
  {
    id: 'bicep-curl',
    name: 'Bicep Curl',
    category: 'strength',
    muscleGroups: ['biceps'],
    isBodyweight: false,
  },
  {
    id: 'tricep-extension',
    name: 'Tricep Extension',
    category: 'strength',
    muscleGroups: ['triceps'],
    isBodyweight: false,
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    category: 'strength',
    muscleGroups: ['back', 'biceps'],
    isBodyweight: false,
  },
  {
    id: 'cable-row',
    name: 'Cable Row',
    category: 'strength',
    muscleGroups: ['back', 'biceps'],
    isBodyweight: false,
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    category: 'strength',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    isBodyweight: false,
  },
  {
    id: 'calf-raises',
    name: 'Calf Raises',
    category: 'strength',
    muscleGroups: ['calves'],
    isBodyweight: false,
  },
  {
    id: 'hip-thrust',
    name: 'Hip Thrust',
    category: 'strength',
    muscleGroups: ['glutes', 'hamstrings'],
    isBodyweight: false,
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    category: 'strength',
    muscleGroups: ['hamstrings', 'glutes', 'back'],
    isBodyweight: false,
  },
  {
    id: 'incline-press',
    name: 'Incline Press',
    category: 'strength',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    isBodyweight: false,
  },
  {
    id: 'face-pulls',
    name: 'Face Pulls',
    category: 'strength',
    muscleGroups: ['shoulders', 'back'],
    isBodyweight: false,
  },
  {
    id: 'treadmill-run',
    name: 'Treadmill Run',
    category: 'cardio',
    muscleGroups: ['legs', 'core', 'cardiovascular'],
    isBodyweight: true,
  },
  {
    id: 'cycling',
    name: 'Cycling',
    category: 'cardio',
    muscleGroups: ['quads', 'cardiovascular'],
    isBodyweight: true,
  },
  {
    id: 'jump-rope',
    name: 'Jump Rope',
    category: 'cardio',
    muscleGroups: ['calves', 'cardiovascular', 'core'],
    isBodyweight: true,
  },
  {
    id: 'swimming',
    name: 'Swimming',
    category: 'cardio',
    muscleGroups: ['back', 'shoulders', 'cardiovascular', 'core'],
    isBodyweight: true,
  },
  {
    id: 'elliptical',
    name: 'Elliptical',
    category: 'cardio',
    muscleGroups: ['legs', 'cardiovascular'],
    isBodyweight: true,
  },
  {
    id: 'rowing-machine',
    name: 'Rowing Machine',
    category: 'cardio',
    muscleGroups: ['back', 'legs', 'cardiovascular', 'core'],
    isBodyweight: true,
  },
  {
    id: 'yoga-flow',
    name: 'Yoga Flow',
    category: 'flexibility',
    muscleGroups: ['full-body', 'core'],
    isBodyweight: true,
  },
  {
    id: 'stretching-session',
    name: 'Stretching Session',
    category: 'flexibility',
    muscleGroups: ['full-body'],
    isBodyweight: true,
  },
  {
    id: 'pilates',
    name: 'Pilates',
    category: 'flexibility',
    muscleGroups: ['core', 'full-body'],
    isBodyweight: true,
  },
  {
    id: 'foam-rolling',
    name: 'Foam Rolling',
    category: 'flexibility',
    muscleGroups: ['full-body'],
    isBodyweight: true,
  },
];
