export const DAILY_QUEST_TEMPLATES = [
  {
    id: 'strength_sets',
    title: 'Iron Session',
    description: 'Complete 3 strength sets',
    icon: 'Dumbbell',
    xpReward: 150,
    type: 'daily',
    goalType: 'strength_sets',
    goal: 3,
  },
  {
    id: 'cardio_time',
    title: 'Cardio Burn',
    description: 'Do 20 minutes of cardio',
    icon: 'Timer',
    xpReward: 150,
    type: 'daily',
    goalType: 'cardio_time',
    goal: 20,
  },
  {
    id: 'flexibility_flow',
    title: 'Flex Flow',
    description: 'Complete 15 minutes of flexibility training',
    icon: 'Activity',
    xpReward: 100,
    type: 'daily',
    goalType: 'flexibility_flow',
    goal: 15,
  },
  {
    id: 'total_reps',
    title: 'Rep Grinder',
    description: 'Rack up 50 total reps',
    icon: 'Repeat',
    xpReward: 175,
    type: 'daily',
    goalType: 'total_reps',
    goal: 50,
  },
  {
    id: 'multi_exercise',
    title: 'Variety Hour',
    description: 'Perform 3 different exercises',
    icon: 'Shuffle',
    xpReward: 200,
    type: 'daily',
    goalType: 'multi_exercise',
    goal: 3,
  },
  {
    id: 'morning_workout',
    title: 'Dawn Warrior',
    description: 'Start a workout before 9 AM',
    icon: 'Sunrise',
    xpReward: 200,
    type: 'daily',
    goalType: 'morning_workout',
    goal: 1,
  },
  {
    id: 'complete_workout',
    title: 'Show Up',
    description: 'Complete any workout today',
    icon: 'CheckCircle',
    xpReward: 100,
    type: 'daily',
    goalType: 'complete_workout',
    goal: 1,
  },
  {
    id: 'heavy_set',
    title: 'Power Hour',
    description: 'Complete a set over 50kg',
    icon: 'Dumbbell',
    xpReward: 225,
    type: 'daily',
    goalType: 'heavy_set',
    goal: 1,
  },
  {
    id: 'squat_sets',
    title: 'Leg Day Initiate',
    description: 'Complete 3 sets of squats',
    icon: 'ChevronDown',
    xpReward: 175,
    type: 'daily',
    goalType: 'squat_sets',
    goal: 3,
  },
  {
    id: 'pushup_reps',
    title: 'Upper Body Blast',
    description: 'Complete 30 push-up reps',
    icon: 'ArrowUp',
    xpReward: 150,
    type: 'daily',
    goalType: 'pushup_reps',
    goal: 30,
  },
];

export const WEEKLY_QUEST_TEMPLATES = [
  {
    id: 'weekly_workouts',
    title: 'Dedicated Athlete',
    description: 'Complete 4 workouts this week',
    icon: 'CalendarCheck',
    xpReward: 500,
    type: 'weekly',
    goalType: 'weekly_workouts',
    goal: 4,
  },
  {
    id: 'weekly_cardio',
    title: 'Endurance Runner',
    description: 'Log 60 minutes of cardio this week',
    icon: 'Heart',
    xpReward: 400,
    type: 'weekly',
    goalType: 'weekly_cardio',
    goal: 60,
  },
  {
    id: 'weekly_strength',
    title: 'Iron Consistent',
    description: 'Complete 3 strength workouts this week',
    icon: 'Dumbbell',
    xpReward: 450,
    type: 'weekly',
    goalType: 'weekly_strength',
    goal: 3,
  },
  {
    id: 'weekly_xp',
    title: 'XP Farmer',
    description: 'Earn 1000 XP from workouts this week',
    icon: 'Sparkles',
    xpReward: 300,
    type: 'weekly',
    goalType: 'weekly_xp',
    goal: 1000,
  },
  {
    id: 'weekly_streak',
    title: 'Never Miss',
    description: 'Work out on 5 different days this week',
    icon: 'Flame',
    xpReward: 600,
    type: 'weekly',
    goalType: 'weekly_streak',
    goal: 5,
  },
];
